# -*- coding: utf-8 -*-
"""SE Exp-01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_qNw-b0esTW1NPjlgBYePbBqNr7CPKj

#Weather modelling using the Qudratic Equation
"""

#quadratic equation y=ax^2+bx+c
a=3
b=4
c=5
x=4.5

y=a*x*x+b*x+c
print("For the values of ",a, " ",b," ",c,"Y is : ",y)
